### ISSUE TITLE
Save export doesn't work

### ISSUE THREAD

**Issue by ExplodingHairyPotatoCat** [Yrahcaz7/Matter-Grid#2]
It just says this 
![image](https://github.com/user-attachments/assets/0945c7be-806f-4ed7-9177-b99ccd9f66a3)
also, your should be "you" in this sentence

**Comment by Yrahcaz7** [comment]
Thank you for this bug report! [This issue should be fixed now.](https://github.com/Yrahcaz7/Matter-Grid/commit/fa8e3c422761e5433341be2fc6aeb1ec9c87dbff)
